engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      no-empty:
        enabled: false
      no-new-func:
        enabled: false
      max-statements:
        enabled: false
      radix:
        enabled: false
      wrap-iife:
        enabled: false
      no-eval:
        enabled: false
  csslint:
    enabled: true
    checks:
      overqualified-elements:
        enabled: false
      errors:
        enabled: false
      text-indent:
        enabled: false
      box-sizing:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"